### ISSUE TITLE
npm run build doesn't work on Windows 10

### ISSUE THREAD

**Issue by ghost** [bcalik/Whatsapp-Desktop#57]
I did what the page told me, just 
`git clone https://github.com/bcalik/Whatsapp-Desktop.git`
`cd WhatsApp-Desktop`
`npm install`
`npm run build`
and this error appears

==================================
                    npm-debug.log
==================================

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle whatsapp-desktop@0.3.3~prebuild: whatsapp-desktop@0.3.3
6 silly lifecycle whatsapp-desktop@0.3.3~prebuild: no script for prebuild, continuing
7 info lifecycle whatsapp-desktop@0.3.3~build: whatsapp-desktop@0.3.3
8 verbose lifecycle whatsapp-desktop@0.3.3~build: unsafe-perm in lifecycle true
9 verbose lifecycle whatsapp-desktop@0.3.3~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\ramm\Desktop\Whatsapp-Desktop-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Users\ramm\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Python36;C:\Program Files\Python36\Scripts;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Users\ramm\AppData\Roaming\npm;
10 verbose lifecycle whatsapp-desktop@0.3.3~build: CWD: C:\Users\ramm\Desktop\Whatsapp-Desktop-master
11 silly lifecycle whatsapp-desktop@0.3.3~build: Args: [ '/d /s /c',
11 silly lifecycle   'npm run clean && npm run build:osx && npm run build:win && npm run build:linux' ]
12 silly lifecycle whatsapp-desktop@0.3.3~build: Returned: code: 1  signal: null
13 info lifecycle whatsapp-desktop@0.3.3~build: Failed to exec build script
14 verbose stack Error: whatsapp-desktop@0.3.3 build: `npm run clean && npm run build:osx && npm run build:win && npm run build:linux`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid whatsapp-desktop@0.3.3
16 verbose cwd C:\Users\ramm\Desktop\Whatsapp-Desktop-master
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error whatsapp-desktop@0.3.3 build: `npm run clean && npm run build:osx && npm run build:win && npm run build:linux`
22 error Exit status 1
23 error Failed at the whatsapp-desktop@0.3.3 build script 'npm run clean && npm run build:osx && npm run build:win && npm run build:linux'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the whatsapp-desktop package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean && npm run build:osx && npm run build:win && npm run build:linux
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs whatsapp-desktop
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls whatsapp-desktop
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
I have the latest versions of node.js, npm and electron

**Comment by Enrico204** [comment]
Development has moved, please open this issue here: https://github.com/Enrico204/Whatsapp-Desktop/issues

**Comment by Enrico204** [comment]
PS: there are new releases after 0.3.3 ;-)

**Comment by ghost** [comment]
I didn't know that, thanks
